// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_logs.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :exec
INSERT INTO audit_logs (
    actor_uuid,
    ip_address,
    user_agent,
    action,
    resource_type,
    resource_uuid,
    request_uuid,
    changes,
    status,
    failure_reason
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
`

type CreateAuditLogParams struct {
	ActorUuid     pgtype.UUID
	IpAddress     string
	UserAgent     string
	Action        string
	ResourceType  string
	ResourceUuid  string
	RequestUuid   pgtype.UUID
	Changes       []byte
	Status        string
	FailureReason pgtype.Text
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.Exec(ctx, createAuditLog,
		arg.ActorUuid,
		arg.IpAddress,
		arg.UserAgent,
		arg.Action,
		arg.ResourceType,
		arg.ResourceUuid,
		arg.RequestUuid,
		arg.Changes,
		arg.Status,
		arg.FailureReason,
	)
	return err
}
