// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth_queries.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserOAuthProvider = `-- name: CreateUserOAuthProvider :one
INSERT INTO user_oauth_providers (
    user_uuid,
    provider,
    provider_user_id,
    provider_email
) VALUES (
    $1,
    $2,
    $3,
    $4
) RETURNING uuid, user_uuid, provider, provider_user_id, provider_email, created_at
`

type CreateUserOAuthProviderParams struct {
	UserUuid       pgtype.UUID
	Provider       OauthProvider
	ProviderUserID string
	ProviderEmail  string
}

func (q *Queries) CreateUserOAuthProvider(ctx context.Context, arg CreateUserOAuthProviderParams) (UserOauthProvider, error) {
	row := q.db.QueryRow(ctx, createUserOAuthProvider,
		arg.UserUuid,
		arg.Provider,
		arg.ProviderUserID,
		arg.ProviderEmail,
	)
	var i UserOauthProvider
	err := row.Scan(
		&i.Uuid,
		&i.UserUuid,
		&i.Provider,
		&i.ProviderUserID,
		&i.ProviderEmail,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUserOAuthProvider = `-- name: DeleteUserOAuthProvider :exec
DELETE FROM user_oauth_providers
WHERE
    uuid = $1
`

func (q *Queries) DeleteUserOAuthProvider(ctx context.Context, uuid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserOAuthProvider, uuid)
	return err
}

const getUserOAuthProviderByProviderAndProviderUserID = `-- name: GetUserOAuthProviderByProviderAndProviderUserID :one
SELECT
    uuid,
    user_uuid,
    provider,
    provider_user_id,
    provider_email,
    created_at
FROM user_oauth_providers
WHERE
    provider = $1 AND provider_user_id = $2
`

type GetUserOAuthProviderByProviderAndProviderUserIDParams struct {
	Provider       OauthProvider
	ProviderUserID string
}

func (q *Queries) GetUserOAuthProviderByProviderAndProviderUserID(ctx context.Context, arg GetUserOAuthProviderByProviderAndProviderUserIDParams) (UserOauthProvider, error) {
	row := q.db.QueryRow(ctx, getUserOAuthProviderByProviderAndProviderUserID, arg.Provider, arg.ProviderUserID)
	var i UserOauthProvider
	err := row.Scan(
		&i.Uuid,
		&i.UserUuid,
		&i.Provider,
		&i.ProviderUserID,
		&i.ProviderEmail,
		&i.CreatedAt,
	)
	return i, err
}

const listUserOAuthProvidersByUserUUID = `-- name: ListUserOAuthProvidersByUserUUID :many
SELECT
    uuid,
    user_uuid,
    provider,
    provider_user_id,
    provider_email,
    created_at
FROM user_oauth_providers
WHERE
    user_uuid = $1
`

func (q *Queries) ListUserOAuthProvidersByUserUUID(ctx context.Context, userUuid pgtype.UUID) ([]UserOauthProvider, error) {
	rows, err := q.db.Query(ctx, listUserOAuthProvidersByUserUUID, userUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserOauthProvider
	for rows.Next() {
		var i UserOauthProvider
		if err := rows.Scan(
			&i.Uuid,
			&i.UserUuid,
			&i.Provider,
			&i.ProviderUserID,
			&i.ProviderEmail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
