// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type OauthProvider string

const (
	OauthProviderGoogle    OauthProvider = "google"
	OauthProviderMicrosoft OauthProvider = "microsoft"
	OauthProviderGithub    OauthProvider = "github"
)

func (e *OauthProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OauthProvider(s)
	case string:
		*e = OauthProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for OauthProvider: %T", src)
	}
	return nil
}

type NullOauthProvider struct {
	OauthProvider OauthProvider
	Valid         bool // Valid is true if OauthProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOauthProvider) Scan(value interface{}) error {
	if value == nil {
		ns.OauthProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OauthProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOauthProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OauthProvider), nil
}

type UserRole string

const (
	UserRoleAdmin UserRole = "admin"
	UserRoleUser  UserRole = "user"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type AuditLog struct {
	Uuid          pgtype.UUID
	ActorUuid     pgtype.UUID
	IpAddress     string
	UserAgent     string
	Action        string
	ResourceType  string
	ResourceUuid  string
	RequestUuid   pgtype.UUID
	Changes       []byte
	Status        string
	FailureReason pgtype.Text
	CreatedAt     pgtype.Timestamptz
}

type AuditLogsDefault struct {
	Uuid          pgtype.UUID
	ActorUuid     pgtype.UUID
	IpAddress     string
	UserAgent     string
	Action        string
	ResourceType  string
	ResourceUuid  string
	RequestUuid   pgtype.UUID
	Changes       []byte
	Status        string
	FailureReason pgtype.Text
	CreatedAt     pgtype.Timestamptz
}

type User struct {
	Uuid         pgtype.UUID
	Name         string
	Email        string
	PasswordHash pgtype.Text
	Role         UserRole
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type UserOauthProvider struct {
	Uuid           pgtype.UUID
	UserUuid       pgtype.UUID
	Provider       OauthProvider
	ProviderUserID string
	ProviderEmail  string
	CreatedAt      pgtype.Timestamptz
}
