// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuthMethodEnum string

const (
	AuthMethodEnumEmail  AuthMethodEnum = "email"
	AuthMethodEnumGoogle AuthMethodEnum = "google"
)

func (e *AuthMethodEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuthMethodEnum(s)
	case string:
		*e = AuthMethodEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for AuthMethodEnum: %T", src)
	}
	return nil
}

type NullAuthMethodEnum struct {
	AuthMethodEnum AuthMethodEnum
	Valid          bool // Valid is true if AuthMethodEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuthMethodEnum) Scan(value interface{}) error {
	if value == nil {
		ns.AuthMethodEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuthMethodEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuthMethodEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuthMethodEnum), nil
}

type User struct {
	Uuid         pgtype.UUID
	Name         string
	Email        string
	PasswordHash pgtype.Text
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	AuthMethod   AuthMethodEnum
}
