// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_query.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email, password_hash, auth_method)
    VALUES ($1, $2, $3, $4)
RETURNING
    uuid, name, email, password_hash, created_at, updated_at, auth_method
`

type CreateUserParams struct {
	Name         string
	Email        string
	PasswordHash pgtype.Text
	AuthMethod   AuthMethodEnum
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.AuthMethod,
	)
	var i User
	err := row.Scan(
		&i.Uuid,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthMethod,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE uuid = $1
`

func (q *Queries) DeleteUser(ctx context.Context, uuid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, uuid)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
    uuid, name, email, password_hash, created_at, updated_at, auth_method
FROM
    users
WHERE
    email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.Uuid,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthMethod,
	)
	return i, err
}

const getUserByUUID = `-- name: GetUserByUUID :one
SELECT
    uuid, name, email, password_hash, created_at, updated_at, auth_method
FROM
    users
WHERE
    uuid = $1
`

func (q *Queries) GetUserByUUID(ctx context.Context, uuid pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUUID, uuid)
	var i User
	err := row.Scan(
		&i.Uuid,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthMethod,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT
    uuid, name, email, password_hash, created_at, updated_at, auth_method
FROM
    users
ORDER BY
    created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.Uuid,
			&i.Name,
			&i.Email,
			&i.PasswordHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthMethod,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :exec
UPDATE
    users
SET
    name = COALESCE($2, name),
    email = COALESCE($3, email),
    password_hash = COALESCE($4, password_hash),
    auth_method = COALESCE($5, auth_method)
WHERE
    uuid = $1
`

type UpdateUserParams struct {
	Uuid         pgtype.UUID
	Name         string
	Email        string
	PasswordHash pgtype.Text
	AuthMethod   AuthMethodEnum
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.Uuid,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.AuthMethod,
	)
	return err
}
